server:
  port: 8090
  url: 'http://127.0.0.1:8090'
db:
  user: "root"
  password: "123456"
  name: "simpletodo"
  host: "127.0.0.1"
  port: "3306"
jwt:
  api_secret: "meowrain"
  token_hour_span: 720