server:
  port: 8090
  url: "http://127.0.0.1:8090"
db:
  user: "simpletodo"
  password: "3tEBhTXKdfpYEtsD"
  name: "simpletodo"
  host: "100.64.0.2"
  port: "3306"
jwt:
  api_secret: "meowrain"
  token_hour_span: 720
